#!/bin/bash
set -euo pipefail

# Script qui liste tous les scripts disponibles avec leur description

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=========================================="
echo "Scripts Disponibles pour le POC"
echo "=========================================="
echo ""

cd "$INSTALL_DIR"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📦 Installation${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}./install_hcd.sh${NC}"
echo "  Installe HCD 1.2.3 (Hyper-Converged Database)"
echo "  - Vérifie Java 11"
echo "  - Extrait HCD"
echo "  - Configure les répertoires de données"
echo ""
echo -e "${GREEN}./install_spark_kafka.sh${NC}"
echo "  Installe Spark 3.5.1, Kafka et spark-cassandra-connector"
echo "  - Télécharge Spark 3.5.1 (compatible Java 11)"
echo "  - Installe Kafka via Homebrew"
echo "  - Télécharge spark-cassandra-connector"
echo "  - Installe les dépendances Python"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🚀 Démarrage${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}./start_hcd.sh [background]${NC}"
echo "  Démarre HCD"
echo "  - Configure Java 11 via jenv"
echo "  - Démarre HCD en premier plan ou en arrière-plan"
echo "  - Usage: ./start_hcd.sh ou ./start_hcd.sh background"
echo ""
echo -e "${GREEN}./start_kafka.sh [background]${NC}"
echo "  Démarre Kafka"
echo "  - Configure Java 17 (requis pour Kafka 4.1.1)"
echo "  - Démarre Kafka en premier plan ou en arrière-plan"
echo "  - Usage: ./start_kafka.sh ou ./start_kafka.sh background"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🔧 Configuration${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}./setup_kafka_hcd_streaming.sh${NC}"
echo "  Configure le streaming Kafka → HCD"
echo "  - Crée le répertoire de checkpoint"
echo "  - Crée le keyspace poc_hbase_migration"
echo "  - Crée la table kafka_events"
echo "  - Vérifie que Kafka et HCD sont démarrés"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🧪 Tests${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}./test_kafka_hcd_streaming.sh${NC}"
echo "  Test complet du pipeline Kafka → HCD"
echo "  - Vérifie que Kafka et HCD sont démarrés"
echo "  - Crée le topic test-topic si nécessaire"
echo "  - Produit des messages de test dans Kafka"
echo "  - Lance un job Spark pour transférer les données vers HCD"
echo "  - Vérifie les données dans HCD"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🛠️  Utilitaires${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}./kafka-helper.sh <commande> [arguments...]${NC}"
echo "  Helper pour utiliser les outils Kafka avec Java 17"
echo "  - Configure automatiquement Java 17"
echo "  - Exécute les commandes Kafka"
echo "  - Exemples:"
echo "    ./kafka-helper.sh kafka-topics.sh --list --bootstrap-server \${KAFKA_BOOTSTRAP_SERVERS:-${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}}"
echo "    ./kafka-helper.sh kafka-console-producer.sh --bootstrap-server \${KAFKA_BOOTSTRAP_SERVERS:-${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}} --topic test-topic"
echo ""
echo -e "${GREEN}./verify_all.sh${NC}"
echo "  Vérifie l'état de tous les composants"
echo "  - Java (version et configuration)"
echo "  - HCD (installation et état)"
echo "  - Spark (installation et version)"
echo "  - Kafka (installation et état)"
echo "  - spark-cassandra-connector"
echo "  - Schémas HCD"
echo "  - Scripts disponibles"
echo ""
echo -e "${GREEN}./list_scripts.sh${NC}"
echo "  Liste tous les scripts disponibles (ce script)"
echo ""
echo -e "${GREEN}./scripts/utils/95_cleanup.sh [--dry-run] [--age DAYS]${NC}"
echo "  Nettoyage automatique du projet"
echo "  - Supprime les répertoires UNLOAD_* de plus de X jours (défaut: 30)"
echo "  - Supprime les fichiers temporaires (.tmp, .bak, .swp, etc.)"
echo "  - Supprime les logs anciens de plus de 90 jours"
echo "  - Options:"
echo "    --dry-run : Simulation sans exécution"
echo "    --age DAYS : Âge maximum des UNLOAD_* à conserver"
echo "  - Usage: ./cleanup.sh --dry-run"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📝 Fichiers Scala de Test${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}kafka_to_hcd_streaming.scala${NC}"
echo "  Job Spark Streaming pour Kafka → HCD"
echo "  - Lit depuis Kafka en streaming"
echo "  - Transforme les données"
echo "  - Écrit vers HCD"
echo ""
echo -e "${YELLOW}test_spark_hcd_connection.scala${NC}"
echo "  Test de connexion Spark → HCD"
echo "  - Crée un keyspace et une table de test"
echo "  - Teste la lecture et l'écriture"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📚 Documentation${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Voir les fichiers .md pour la documentation complète :"
echo "  - GUIDE_INSTALLATION_HCD_MAC.md"
echo "  - GUIDE_INSTALLATION_SPARK_KAFKA.md"
echo "  - KAFKA_HCD_STREAMING_READY.md"
echo "  - RESULTATS_TEST_KAFKA_HCD.md"
echo ""
